---

  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: "{{resource_group}}"
      name: networkSecurityGroup
      rules:
        - name: 'allow_ssh'
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 'allow_web_traffic'
          protocol: Tcp
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 1002
          direction: Inbound

